package com.cn.model;

public class CarType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_type.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_type.type
     *
     * @mbggenerated
     */
    private String type;

    public CarType() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_type
     *
     * @mbggenerated
     */

    public CarType(String id, String type) {
        this.id = id;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_type.Id
     *
     * @return the value of t_car_type.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_type.type
     *
     * @return the value of t_car_type.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setType(String type) {
        this.type = type;
    }
}