package com.cn.model;

import java.util.Date;

public class OrderH extends Order{


    private String orderId;

    private Date optTime;

    private User optUser;

    public OrderH() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_h
     *
     * @mbggenerated
     */

    /*public OrderH(String id, String orderId, String orderNo, String type, Date startTime, String tenancy, String startAddress, String endAddress, String fetchSend, String flightTrain, String single, String fee, String total, String status, String remark, String customerId, String customerType, String customerName, String customerMobile, String customerCarType, String supplierId, String supplierName, String carId, String plateNumber, String carType, String driverId, String driverName, String driverMobile, Date createTime, Date optTime,String optId,String optName) {

        super(id, orderNo, type, startTime, tenancy, startAddress, endAddress, fetchSend, flightTrain, single, fee, total, status, remark, customerId, customerType, customerName, customerMobile, customerCarType, supplierId, supplierName, carId, plateNumber, carType, driverId, driverName, driverMobile, createTime);
        this.orderId = orderId;
        this.optTime = optTime;
        this.optId=optId;
        this.optName=optName;
    }
*/
    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public Date getOptTime() {
        return optTime;
    }

    public void setOptTime(Date optTime) {
        this.optTime = optTime;
    }

    public User getOptUser() {
        return optUser;
    }

    public void setOptUser(User optUser) {
        this.optUser = optUser;
    }
}