package com.cn.model;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.tenancy
     *
     * @mbggenerated
     */
    private String tenancy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.start_address
     *
     * @mbggenerated
     */
    private String startAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.end_address
     *
     * @mbggenerated
     */
    private String endAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.fetch_send
     *
     * @mbggenerated
     */
    private String fetchSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.flight_train
     *
     * @mbggenerated
     */
    private String flightTrain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.single
     *
     * @mbggenerated
     */
    private String single;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.fee
     *
     * @mbggenerated
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total
     *
     * @mbggenerated
     */
    private BigDecimal total;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbggenerated
     */

    private BigDecimal commission;
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_id
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_type
     *
     * @mbggenerated
     */
    private String customerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_name
     *
     * @mbggenerated
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_mobile
     *
     * @mbggenerated
     */
    private String customerMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_car_type
     *
     * @mbggenerated
     */
    private String customerCarType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.supplier_id
     *
     * @mbggenerated
     */
    private String supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.supplier_name
     *
     * @mbggenerated
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.car_id
     *
     * @mbggenerated
     */
    private String carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.plate_number
     *
     * @mbggenerated
     */
    private String plateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.car_type
     *
     * @mbggenerated
     */
    private String carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.driver_id
     *
     * @mbggenerated
     */
    private String driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.driver_name
     *
     * @mbggenerated
     */
    private String driverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.driver_mobile
     *
     * @mbggenerated
     */
    private String driverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;
    private Date lastOptTime;

    public Order() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */

    public Order(String id, String orderNo, String type, Date startTime, String tenancy, String startAddress, String endAddress, String fetchSend, String flightTrain, String single, BigDecimal fee, BigDecimal total,BigDecimal commission, String status, String remark, String customerId, String customerType, String customerName, String customerMobile, String customerCarType, String supplierId, String supplierName, String carId, String plateNumber, String carType, String driverId, String driverName, String driverMobile, Date createTime,Date lastOptTime) {
        this.id = id;
        this.orderNo = orderNo;
        this.type = type;
        this.startTime = startTime;
        this.tenancy = tenancy;
        this.startAddress = startAddress;
        this.endAddress = endAddress;
        this.fetchSend = fetchSend;
        this.flightTrain = flightTrain;
        this.single = single;
        this.fee = fee;
        this.total = total;
        this.commission=commission;
        this.status = status;
        this.remark = remark;
        this.customerId = customerId;
        this.customerType = customerType;
        this.customerName = customerName;
        this.customerMobile = customerMobile;
        this.customerCarType = customerCarType;
        this.supplierId = supplierId;
        this.supplierName = supplierName;
        this.carId = carId;
        this.plateNumber = plateNumber;
        this.carType = carType;
        this.driverId = driverId;
        this.driverName = driverName;
        this.driverMobile = driverMobile;
        this.createTime = createTime;
        this.lastOptTime=lastOptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.Id
     *
     * @return the value of t_order.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_no
     *
     * @return the value of t_order.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.type
     *
     * @return the value of t_order.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.start_time
     *
     * @return the value of t_order.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.tenancy
     *
     * @return the value of t_order.tenancy
     *
     * @mbggenerated
     */
    public String getTenancy() {
        return tenancy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.start_address
     *
     * @return the value of t_order.start_address
     *
     * @mbggenerated
     */
    public String getStartAddress() {
        return startAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.end_address
     *
     * @return the value of t_order.end_address
     *
     * @mbggenerated
     */
    public String getEndAddress() {
        return endAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.fetch_send
     *
     * @return the value of t_order.fetch_send
     *
     * @mbggenerated
     */
    public String getFetchSend() {
        return fetchSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.flight_train
     *
     * @return the value of t_order.flight_train
     *
     * @mbggenerated
     */
    public String getFlightTrain() {
        return flightTrain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.single
     *
     * @return the value of t_order.single
     *
     * @mbggenerated
     */
    public String getSingle() {
        return single;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.fee
     *
     * @return the value of t_order.fee
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.total
     *
     * @return the value of t_order.total
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.remark
     *
     * @return the value of t_order.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_id
     *
     * @return the value of t_order.customer_id
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_type
     *
     * @return the value of t_order.customer_type
     *
     * @mbggenerated
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_name
     *
     * @return the value of t_order.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_mobile
     *
     * @return the value of t_order.customer_mobile
     *
     * @mbggenerated
     */
    public String getCustomerMobile() {
        return customerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_car_type
     *
     * @return the value of t_order.customer_car_type
     *
     * @mbggenerated
     */
    public String getCustomerCarType() {
        return customerCarType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.supplier_id
     *
     * @return the value of t_order.supplier_id
     *
     * @mbggenerated
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.supplier_name
     *
     * @return the value of t_order.supplier_name
     *
     * @mbggenerated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.car_id
     *
     * @return the value of t_order.car_id
     *
     * @mbggenerated
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.plate_number
     *
     * @return the value of t_order.plate_number
     *
     * @mbggenerated
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.car_type
     *
     * @return the value of t_order.car_type
     *
     * @mbggenerated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.driver_id
     *
     * @return the value of t_order.driver_id
     *
     * @mbggenerated
     */
    public String getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.driver_name
     *
     * @return the value of t_order.driver_name
     *
     * @mbggenerated
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.driver_mobile
     *
     * @return the value of t_order.driver_mobile
     *
     * @mbggenerated
     */
    public String getDriverMobile() {
        return driverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_time
     *
     * @return the value of t_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public void setTenancy(String tenancy) {
        this.tenancy = tenancy;
    }

    public void setStartAddress(String startAddress) {
        this.startAddress = startAddress;
    }

    public void setEndAddress(String endAddress) {
        this.endAddress = endAddress;
    }

    public void setFetchSend(String fetchSend) {
        this.fetchSend = fetchSend;
    }

    public void setFlightTrain(String flightTrain) {
        this.flightTrain = flightTrain;
    }

    public void setSingle(String single) {
        this.single = single;
    }

    public BigDecimal getFee() {
        return fee;
    }

    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    public BigDecimal getTotal() {
        return total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public void setCustomerMobile(String customerMobile) {
        this.customerMobile = customerMobile;
    }

    public void setCustomerCarType(String customerCarType) {
        this.customerCarType = customerCarType;
    }

    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    public void setCarId(String carId) {
        this.carId = carId;
    }

    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }

    public void setCarType(String carType) {
        this.carType = carType;
    }

    public void setDriverId(String driverId) {
        this.driverId = driverId;
    }

    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }

    public void setDriverMobile(String driverMobile) {
        this.driverMobile = driverMobile;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public BigDecimal getCommission() {
        return commission;
    }

    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    public Date getLastOptTime() {
        return lastOptTime;
    }

    public void setLastOptTime(Date lastOptTime) {
        this.lastOptTime = lastOptTime;
    }
}