package com.cn.model;

public class Picture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.remark
     *
     * @mbggenerated
     */
    private String remark;

    public Picture() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_picture
     *
     * @mbggenerated
     */

    public Picture(String id, String name, String type, Integer seq, String url, String status, String remark) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.seq = seq;
        this.url = url;
        this.status = status;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.Id
     *
     * @return the value of t_picture.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.name
     *
     * @return the value of t_picture.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.type
     *
     * @return the value of t_picture.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.seq
     *
     * @return the value of t_picture.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.url
     *
     * @return the value of t_picture.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.status
     *
     * @return the value of t_picture.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.remark
     *
     * @return the value of t_picture.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}