package com.cn.model;

import java.util.Date;

public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    public Supplier() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbggenerated
     */

    public Supplier(String id, String mobile, String name, String contactName,String status, String remark, Date createTime) {
        this.id = id;
        this.mobile = mobile;
        this.name = name;
        this.contactName=contactName;
        this.status = status;
        this.remark = remark;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.Id
     *
     * @return the value of t_supplier.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.mobile
     *
     * @return the value of t_supplier.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.name
     *
     * @return the value of t_supplier.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.status
     *
     * @return the value of t_supplier.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.remark
     *
     * @return the value of t_supplier.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.create_time
     *
     * @return the value of t_supplier.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
}