package com.cn.vo;

import com.cn.model.Menu;
public class MenuEx {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column t_menu.Id
         *
         * @mbggenerated
         */
        private String id;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column t_menu.name
         *
         * @mbggenerated
         */
        private String name;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column t_menu.seq
         *
         * @mbggenerated
         */
        private Integer seq;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column t_menu.parent_id
         *
         * @mbggenerated
         */
        private String parentId;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column t_menu.ulr
         *
         * @mbggenerated
         */
        private String url;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column t_menu.icon
         *
         * @mbggenerated
         */
        private String icon;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_menu
         *
         * @mbggenerated
         */

        private String isLeaf;
        private String  roleId;

    public MenuEx() {
    }

    public MenuEx(String id, String name, Integer seq, String parentId, String url, String icon, String isLeaf, String roleId) {
            this.id = id;
            this.name = name;
            this.seq = seq;
            this.parentId = parentId;
            this.url = url;
            this.icon = icon;
            this.isLeaf=isLeaf;
            this.roleId=roleId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column t_menu.Id
         *
         * @return the value of t_menu.Id
         *
         * @mbggenerated
         */
        public String getId() {
            return id;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column t_menu.name
         *
         * @return the value of t_menu.name
         *
         * @mbggenerated
         */
        public String getName() {
            return name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column t_menu.seq
         *
         * @return the value of t_menu.seq
         *
         * @mbggenerated
         */

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column t_menu.parent_id
         *
         * @return the value of t_menu.parent_id
         *
         * @mbggenerated
         */
        public String getParentId() {
            return parentId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column t_menu.ulr
         *
         * @return the value of t_menu.ulr
         *
         * @mbggenerated
         */


        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column t_menu.icon
         *
         * @return the value of t_menu.icon
         *
         * @mbggenerated
         */
        public String getIcon() {
            return icon;
        }

        public String getIsLeaf() {
            return isLeaf;
        }

        public void setIsLeaf(String isLeaf) {
            this.isLeaf = isLeaf;
        }

        public void setId(String id) {
            this.id = id;
        }

        public void setName(String name) {
            this.name = name;
        }



        public void setParentId(String parentId) {
            this.parentId = parentId;
        }


    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getSeq() {
        return seq;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    public void setIcon(String icon) {
            this.icon = icon;
        }

    public String getRoleId() {
        return roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}